#!/bin/bash
if [ $1 == "" ]; then
    echo $"Usage: $0 {backend|down|run|docker-restart}"
    exit 0
fi

case $1 in
    backend)
        mkdir -p ./tmp/{db/backup,pyenv,data,cache/pypoetry}
        docker-compose -f docker/docker-compose.dev.yml run -p 8000:8000 backend zsh
        ;;
    initdir)
        mkdir -p /data/{geo,logs}
        mkdir -p /data/attachments/{media,avatar,cache/metadata_thumbnails}
        mkdir -p /data/attachments/media/{images,videos,audios,others}
        if [ -f "$DJANGO_LOG_FILE" ]; then
            echo "$DJANGO_LOG_FILE exists."
        else 
            touch "$DJANGO_LOG_FILE"
            echo "$DJANGO_LOG_FILE does not exist. created"
        fi
        ;;
    run)
        poetry run python3 manage.py migrate
        poetry run python3 manage.py runserver 0.0.0.0:8000
        ;;
    mkmsg)
        poetry run python3 manage.py makemessages -l en
        ;;
    comsg)
        poetry run python3 manage.py compilemessages -l en
        ;;
    makemigrations)
        poetry run python3 manage.py makemigrations
        ;;
    createsuperuser)
        poetry run python3 manage.py createsuperuser
        ;;
    migrate)
        poetry run python3 manage.py migrate
        ;;
    test)
        poetry run python3 manage.py test
        ;;
    coverage)
        poetry run coverage run --source='.' manage.py test
        poetry run coverage report
        ;;
    down)
        docker-compose -f docker/docker-compose.dev.yml down
        ;;
    docker-restart)
        docker start $(docker ps -a -q -f status=exited)
        ;;
    -h | --help)
        echo $"Usage: $0 {backend|down|run|docker-restart}"
        ;;
esac
