apiVersion: batch/v1
kind: Job
metadata:
  name: ios-capstone-django-test
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ios-capstone-django-test
          image: freeyeti/dev-in-docker:python3-gis
          imagePullPolicy: Always
          command: ["./docker-entrypoint-test.sh"]
          envFrom:
            - configMapRef:
                name: ios-capstone-env-config
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: app.settings_build
          volumeMounts:
            - name: code
              mountPath: /code
      volumes:
        - name: code
          hostPath:
            path: __CODE_PATH__