# Generated by Django 3.2.9 on 2022-08-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photos',
            table='photos',
        ),
    ]
