# Generated by Django 3.2.9 on 2022-08-05 20:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
