# Generated by Django 3.2.9 on 2022-08-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photos_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='thumb_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
